---

- name: Deploy HAProxy configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/haproxy/conf.d/{{ item }}"
    owner: "root"
    group: "root"
  with_items:
    - midonet_cluster

- name: Regenerate HAProxy configuration
  assemble:
    src: "/etc/haproxy/conf.d"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart HAProxy
